#!/bin/tcsh

set echo
set plotdir = 'autoplots'
if ( ! -e $plotdir ) mkdir $plotdir

foreach i ( parthenon.prim.?????.phdf )
    set fname = `basename $i .phdf`

    if ( ` ls $plotdir/$fname* |wc -l` >0 ) then
        continue
    else
        #If more than one instance of plotme is running,
        #this prevents them from working on the same files.
        touch $plotdir/$fname.mine 
       yt plot -p -a 0 --show-grids -o $plotdir -f density $i
       rm $plotdir/$fname.mine
    endif
    
end

#end
