#!/bin/tcsh
#set echo

#
# usage:
# slaunch slurm_job.sbatch number_of_repeats
# 
# Launches several dependent jobs in a slurm way.
# Also launches a sidecar job.  The intention of this is for 
# making tar files and images.
#
# NOGO is a fail safe in case Enzo fails or runs successfully.
# In either event, you need to examine the state of the code.
#
#set echo
set sidecar = $HOME/repos/slaunch/PlotAndTar.sbatch
#set sidecar = $HOME/repos/slaunch/PlotAthena.sbatch
#set sidecar = $HOME/repos/slaunch/AnalysisAthena.sbatch

set job = $1
shift
if ( $#argv >= 0 ) then
    set number = $1
    shift
else
    set number = 1
endif

set do_autodep = False
set depend = None
set sidecar = None
while( $#argv )
    switch( $1 )
    case "-s":
        shift
        set sidecar = $1
        shift
        breaksw
    case "--autodep":
        set do_autodep = True
        shift
        breaksw
    case "--d":
        shift
        set depend = $1
        shift
        breaksw
    default:
        echo "Unrecognized argument" $1
        exit
    

    endsw
end

if ( $do_autodep == True ) then
    set CWD = `pwd`
    set simname = `basename $CWD`
    set fname_list = `find . -name "$simname.o*"`
    if ( $#fname_list > 0 ) then
        set fname = `ls $simname.o* |sort | tail -1`
        set jobid = `echo $fname | sed -e 's/\(.*\).o\([0-9]\+\)/\2/'`
        if ( `showq -u |grep $jobid |wc -l` > 0 ) then
            #job is running, set as dependency
            set depend = $jobid
        endif
    endif
endif

set first_dep = ""
if ( $depend != None ) then
    set first_dep = "--dependency=afterany:$depend"
endif


if ( ! -e $job ) then
    echo "job not found" $job
    exit -1
endif

if ( -e NOGO ) then
    echo "Jobs will not launch.  NOGO present"
    exit -1
endif


set count = 1
set dep = `sbatch --parsable $first_dep $job |tail -1`
echo "Job" $dep $first_dep

set tarjob = `sbatch --parsable --dependency=afterany:$dep $sidecar | tail -1`
echo "tar" $tarjob

while ( $count < $number )
    @ count++
    set dep = `sbatch --parsable --dependency=afterany:$dep $job |tail -1`
    echo "Job " $dep
    set tarjob = `sbatch --parsable --dependency=afterany:$dep $sidecar |tail -1`
    echo "tar" $tarjob
end

#end
